CREATE TABLE IF NOT EXISTS wechat_public_account (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    avatarUrl VARCHAR(500) DEFAULT NULL,
    appId VARCHAR(128) DEFAULT NULL UNIQUE,
    appSecret VARCHAR(128) DEFAULT NULL UNIQUE,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    isActive TINYINT(1) NOT NULL DEFAULT 1,
    token VARCHAR(32) DEFAULT NULL,
    encodingAESKey VARCHAR(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
